<?php include __DIR__."\lib\\route\Route.php"; ?>
<?php include __DIR__.'\lib/controllers/PublicController.php'; ?>
<?php include __DIR__.'\partials/header.php' ?>
<?php include __DIR__.'\partials/top_section.php' ?>
<?php include __DIR__.'\partials/carousel.php' ?>
<?php include __DIR__.'\partials/info.php' ?>
<?php include __DIR__.'\partials/featured.php' ?>
<?php include __DIR__.'\partials/advertise.php' ?>
<?php include __DIR__.'\partials/footer.php' ?>